CREATE TABLE IF NOT EXISTS employees (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name   TEXT NOT NULL,
  last_name    TEXT NOT NULL,
  email        TEXT UNIQUE NOT NULL,
  department   TEXT NOT NULL,
  title        TEXT NOT NULL,
  salary       NUMERIC(12,2) NOT NULL CHECK (salary >= 0),
  hire_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  manager_id   INTEGER NULL,
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','on_leave','terminated')),
  -- Handy computed constraints
  CONSTRAINT email_format CHECK (
    email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  )
);

-- Self-referencing manager FK (defer adding until table exists)
ALTER TABLE employees
  ADD CONSTRAINT fk_employees_manager
  FOREIGN KEY (manager_id)
  REFERENCES employees (id)
  ON UPDATE CASCADE
  ON DELETE SET NULL;

ALTER TABLE employees
ADD CONSTRAINT chk_no_self_manager
CHECK (manager_id IS NULL OR manager_id <> id);


-- Seed 150 employees for practice (PostgreSQL)
-- Adjust schema/search_path if needed. Targets table: employees

INSERT INTO employees (
  id, first_name, last_name, email, department, title, salary, hire_date, manager_id, status
)
SELECT
  gs AS id,
  (ARRAY['Ava','Ben','Cara','Diego','Ella','Finn','Grace','Hugo','Ivy','Jack',
          'Kara','Liam','Mia','Noah','Olive','Pia','Quinn','Ravi','Sara','Theo']
  )[(gs-1) % 20 + 1] AS first_name,
  (ARRAY['Li','Smith','Patel','Garcia','Brown','Kim','Johnson','Singh','Martinez','Davis',
          'Chen','Wilson','Anderson','Thomas','White','Lopez','Lee','Walker','Young','Hall']
  )[(gs-1) % 20 + 1] AS last_name,
  'user' || gs || '@example.com' AS email,
  (ARRAY['Engineering','Product','Design','Sales','Marketing','HR','Finance','Operations','Support','Data']
  )[(gs-1) % 10 + 1] AS department,
  CASE ((gs-1) % 10 + 1)
    WHEN 1 THEN (CASE WHEN gs % 5 = 0 THEN 'Senior Software Engineer'
                      WHEN gs % 5 = 1 THEN 'Software Engineer'
                      WHEN gs % 5 = 2 THEN 'DevOps Engineer'
                      WHEN gs % 5 = 3 THEN 'QA Engineer'
                      ELSE 'Data Engineer' END)
    WHEN 2 THEN (CASE WHEN gs % 3 = 0 THEN 'Senior Product Manager' ELSE 'Product Manager' END)
    WHEN 3 THEN (CASE WHEN gs % 3 = 0 THEN 'Senior Designer' ELSE 'Designer' END)
    WHEN 4 THEN (CASE WHEN gs % 3 = 0 THEN 'Sales Manager' ELSE 'Sales Rep' END)
    WHEN 5 THEN (CASE WHEN gs % 3 = 0 THEN 'Marketing Manager' ELSE 'Marketing Specialist' END)
    WHEN 6 THEN (CASE WHEN gs % 3 = 0 THEN 'HR Manager' ELSE 'HR Generalist' END)
    WHEN 7 THEN (CASE WHEN gs % 3 = 0 THEN 'Finance Manager' ELSE 'Finance Analyst' END)
    WHEN 8 THEN (CASE WHEN gs % 3 = 0 THEN 'Operations Manager' ELSE 'Operations Coordinator' END)
    WHEN 9 THEN (CASE WHEN gs % 3 = 0 THEN 'Support Lead' ELSE 'Support Engineer' END)
    WHEN 10 THEN (CASE WHEN gs % 3 = 0 THEN 'Senior Data Analyst' ELSE 'Data Analyst' END)
  END AS title,
  ROUND((50000 + ((gs % 101) * 1200))::numeric, 2) AS salary,
  (DATE '2015-01-01' + ((gs * 17) % 4015)) AS hire_date,
  CASE WHEN gs <= 10 THEN NULL ELSE ((gs % 10) + 1) END AS manager_id,
  CASE WHEN gs % 20 = 0 THEN 'terminated'
       WHEN gs % 9 = 0 THEN 'on_leave'
       ELSE 'active' END AS status
FROM generate_series(1,150) AS gs
ON CONFLICT DO NOTHING;
